#!/bin/bash

# Move existing Flatpak user data to the new location
# ${XDG_DATA_HOME} -> ${XDG_DATA_HOME}/q3a
if [ -f "${XDG_DATA_HOME}/qkey" -a ! -d "${XDG_DATA_HOME}/q3a" ]; then
	mv "${XDG_DATA_HOME}" "${XDG_DATA_HOME}/../q3a-tmp"
	mkdir "${XDG_DATA_HOME}"
	mv "${XDG_DATA_HOME}/../q3a-tmp" "${XDG_DATA_HOME}/q3a"
fi

/app/games/quake3/ioquake3 "${@}"
